apiVersion: v1
kind: Service
metadata:
  name: learnalgorithm-backend
  namespace: learnalgorithm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: learnalgorithm-backend
