apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnalgorithm
  namespace: learnalgorithm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  rules:
    - host: learnalgorithm.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: learnalgorithm-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnalgorithm-frontend
                port:
                  number: 3000
